theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
title: " "
description: "Virtual workshop on the subcortex, Amsterdam, March 1-3, 2021"
logo: workshop-logo2.png
show_downloads: false
